version: '3'
services:
    worker1:
        image: worker
        container_name: worker1
        ports:
            - "10101:8080"
        volumes:
            - vol_1:/shared
        environment:
            - id=1
            
    worker2:
        image: worker
        container_name: worker2
        ports:
            - "10102:8080"
        volumes:
            - vol_2:/shared
        environment:
            - id=2
        
    worker3:
        image: worker
        container_name: worker3
        ports:
            - "10103:8080"
        volumes:
            - vol_3:/shared
        environment:
            - id=3           
            
    worker4:
        image: worker
        container_name: worker4
        ports:
            - "10104:8080"
        volumes:
            - vol_4:/shared
        environment:
            - id=4
networks:
    default:
        external:
            name: mainNet
        
volumes:
    vol_1:
    vol_2:
    vol_3:
    vol_4:
    
        