version: '3'
services:
    worker1:
        image: worker
        container_name: worker1
        ports:
            - "10101:8080"
        volumes:
            - worker_vol_1:/shared
            
    worker2:
        image: worker
        container_name: worker2
        ports:
            - "10102:8080"
        volumes:
            - worker_vol_2:/shared
        
    worker3:
        image: worker
        container_name: worker3
        ports:
            - "10103:8080"
        volumes:
            - worker_vol_3:/shared
            
    worker4:
        image: worker
        container_name: worker4
        ports:
            - "10104:8080"
        volumes:
            - worker_vol_4:/shared
networks:
    default:
        external:
            name: mainNet
        
volumes:
    worker_vol_1:
    worker_vol_2:
    worker_vol_3:
    worker_vol_4:
    
        